### ISSUE TITLE
HIPE Compiler

### ISSUE THREAD

**Issue by AndrewDryga** [bitwalker/alpine-erlang#1]
Hi,

I'm trying to build RabbitMQ container that is based on this image, but when i turn on HIPE compiler in MQ it ignores it with error message: 
```
Not HiPE compiling: HiPE not found in this Erlang installation.
=WARNING REPORT==== 29-Aug-2016::00:29:26 ===
Not HiPE compiling: HiPE not found in this Erlang installation.
=INFO REPORT==== 29-Aug-2016::00:29:28 ===
```

Maybe you can suggest better way to use HIPE compiler on alpine distros?

**Comment by bitwalker** [comment]
Simply `apk add erlang-hipe` as part of your Dockerfile and you'll be good to go :)

**Comment by AndrewDryga** [comment]
It's already included: https://github.com/bitwalker/alpine-erlang/blob/master/Dockerfile#L22

**Comment by bitwalker** [comment]
That's strange, the package must be broken, I'll see what I can find out.

**Comment by AndrewDryga** [comment]
Any success? Maybe we should reopen issue?

**Comment by bitwalker** [comment]
This is now fixed in the latest release. (tagged 19.0.1 and latest)

**Comment by edmorley** [comment]
This same issue is affecting the official docker rabbitmq image (docker-library/rabbitmq#151).

Did you find out why the alpine erlang-hipe package didn't work?
Has this been reported to the package maintainer? :-)

**Comment by bitwalker** [comment]
It's been quite awhile now, so I don't recall what I found, but I don't remember finding anything specifically wrong with the `erlang-hipe` package. I do know part of why I switched to building from source was because I had more control over what and how things were included, and hipe was part of that. There is probably something about the way the official `erlang-hipe` package is being produced that needs to change, but I couldn't tell you what exactly; but my recommendation is that if anyone on Alpine needs it, they should build Erlang from source for now.

**Comment by lnshi** [comment]
@bitwalker  I thought someone already figured out the cause: [here](https://bugs.alpinelinux.org/issues/5700) ?

BTW, with latest [3.6.10-management](https://hub.docker.com/r/library/rabbitmq/tags/) still get:

```
=WARNING REPORT==== 21-Jun-2017::04:21:09 ===
Not HiPE compiling: HiPE not found in this Erlang installation.
```
